### ISSUE TITLE
Instead of GIFs, use screenshots of each step with their description

### ISSUE THREAD

**Issue by NightMachinary** [Sambigeara/fuzzynote#70]

**Comment by Sambigeara** [comment]
Hello! Thanks for the feedback.

I think what this highlights (confirms) to me is that my documentation is lacking at best... the reason for the GIFs was to try and give some high level demo of the functionality, rather than as a guide for use. I could definitely do a better job of documenting the various features.

Out of interest, is there an aspect that is particularly confusing or frustrating? I could use that to start prioritising what to improve or add to first!

**Comment by Sambigeara** [comment]
Closing for now.
