### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [Sambigeara/fuzzynote#73]
First, thank you for sharing this project with us!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by Sambigeara** [comment]
Hi @mbrukman - thank you for taking the time to check it out!

Admittedly, I've held off choosing a license thus far because quite frankly, it's an area I know very little about and I wanted to make a thoughtful decision.

Perhaps this is an opportunity to gather some feedback - I was loosely considering GPL/AGPL, would either of these impact how you viewed/approached the project? Appreciate any thoughts or insight at all.

Cheers

**Comment by kseistrup** [comment]
I appreciate projects with a GPL license: I know I can “mix and match” any code I see in any of my own projects, with the condition that my code is release under the same or a similarly free license. That's fair. I usually choose GPL3 for my own projects.

**Comment by Sambigeara** [comment]
Thanks for the input. I'm erring strongly on the side of AGPL. If no strong counter-points appear, I'll pull the trigger in the next day or so.
